name : simple go build

on :
  push:
    branches : [ main ]


jobs:
  checkout : 
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

  process:
    runs-on: ubuntu-22.04
    
    steps:
      - name: run one-line script
        run: echo hello, world!
      - name : runs a multi-line code
        run : |
           echo Add other actions to build,
           echo test, and deploy your project.

      
      
